### ISSUE TITLE
Update function does not work

### ISSUE THREAD

**Issue by ratio91** [Endogen/Telegram-Kraken-Bot#21]
**/update** command causes the file _telegram_kraken_bot.py_ to get corrupted (empty).
(seems to be fixed in the latest version, only older clients are affected apparently - I guess they just need to pull the file from github manually)

**Comment by Endogen** [comment]
Yes. There is no other way to resolve it...

I can't rule out the possibility that the `/update` command will not work in the future because in some cases i can't update the key names in config file (if the name changes because i rename it). But i can quarantee that i will not rename key names in config as soon as we reach version 1.0

Feel free to reopen the issue if you need more info or have questions regarding this issue
