### ISSUE TITLE
Possible private key leak

### ISSUE THREAD

**Issue by fuomag9** [Endogen/Telegram-Kraken-Bot#30]
On commit c144aea15a886077abc9bbd49feab9462c4c8c2c there are personal keys. I've not tested them, are you sure they are not active anymore?

**Comment by Endogen** [comment]
Hey thanks for the notice :-)

I know about that. I stupidly commited the keys, then noticed it and immediately changed them. Since it's not possible to remove the commit, it's in there forever. Only thing i could do is remove the repo and create it again.

But again, no danger here, keys are for sure not valid for a long time now. But thanks again! 👍
